AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Description: The deployment environment
    Type: String

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        APP_TABLE_NAME: !Ref LinksTable

Resources:  
  VisitLinkFunction:
    Metadata:
      BuildMethod: rust-cargolambda
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/visit_link
      Handler: bootstrap
      FunctionName: !Sub VisitLinkFunction-${Env}
      Runtime: provided.al2023
      Architectures:
        - arm64
      Events:
        GetLinks:
          Type: HttpApi
          Properties:
            Path: /{linkId}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable

  CreateLinkFunction:
    Metadata:
      BuildMethod: rust-cargolambda
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/create_link
      Handler: bootstrap
      FunctionName: !Sub CreateLinkFunction-${Env}
      Runtime: provided.al2023
      Architectures:
        - arm64
      Events:
        CreateLink:
          Type: HttpApi
          Properties:
            Path: /links
            Method: POST
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref LinksTable
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Env}/url-shortener/config
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref ApplicationSecret

  GetLinksFunction:
    Metadata:
      BuildMethod: rust-cargolambda
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/get_links
      Handler: bootstrap
      FunctionName: !Sub GetLinksFunction-${Env}
      Runtime: provided.al2023
      Architectures:
        - arm64
      Events:
        GetLinks:
          Type: HttpApi
          Properties:
            Path: /links
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref LinksTable
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Env}/url-shortener/config
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref ApplicationSecret

  LinksTable:
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub LinksTable-${Env}
      KeySchema:
        - AttributeName: LinkId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: LinkId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

Outputs:
  LinksTableName:
    Description: "LinksTable name"
    Export:
      Name: !Sub LinksTableName-${Env}
    Value: !Ref LinksTable
  UrlShortenerEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: !Sub UrlShortenerEndpoint-${Env}
